name: Main

on: push

jobs:
  windows:
    name: Windows

    runs-on: windows-latest

    steps:

    - name: Checkout opensim-core main
      uses: actions/checkout@v4
      with:
         repository: opensim-org/opensim-core
         path: 'opensim-core'

    - name: Install SWIG
      run: |
        choco install swig --version 4.1.1 --yes --limit-output --allow-downgrade
        swig -swiglib

    - name: Install Python packages
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install numpy
      run: python3 -m pip install numpy==1.26

    - name: Checkout opensim-core main
      uses: actions/checkout@v3
      with:
         repository: opensim-org/opensim-core
         path: 'opensim-core'
    
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ~/opensim_dependencies_install
        # Every time a cache is created, it's stored with this key.
        # In subsequent runs, if the key matches the key of an existing cache,
        # then the cache is used. We chose for this key to depend on the
        # operating system and a hash of the hashes of all files in the
        # dependencies directory (non-recursive).
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
        key: ${{ runner.os }}-dependencies-${{ hashFiles('opensim-core/dependencies/*') }}

    - name: Build dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        echo $env:GITHUB_WORKSPACE\\build_deps
        mkdir $env:GITHUB_WORKSPACE\\build_deps
        chdir $env:GITHUB_WORKSPACE\\build_deps
        # /W0 disables warnings.
        # https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx
        # TODO: CMake provides /W3, which overrides our /W0
        cmake -E env CXXFLAGS="/W0" cmake $env:GITHUB_WORKSPACE/opensim-core/dependencies -LAH -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=~/opensim_dependencies_install -DSUPERBUILD_ezc3d=ON -DOPENSIM_WITH_TROPTER=ON -DOPENSIM_WITH_CASADI=ON
        cmake --build . --config Release -- /maxcpucount:4
        
    - name: Configure opensim-core
      id: configure
      run: |
        mkdir $env:GITHUB_WORKSPACE\\build
        chdir $env:GITHUB_WORKSPACE\\build
        # TODO: Can remove /WX when we use that in CMakeLists.txt.
        # Set the CXXFLAGS environment variable to turn warnings into errors.
        # Skip timing test section included by default.
        cmake -E env CXXFLAGS="/WX -DSKIP_TIMING" cmake $env:GITHUB_WORKSPACE -LAH -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=~/opensim-core-install -DOPENSIM_DEPENDENCIES_DIR=~/opensim_dependencies_install -DOPENSIM_C3D_PARSER=ezc3d -DBUILD_PYTHON_WRAPPING=on -DBUILD_JAVA_WRAPPING=on -DOPENSIM_WITH_TROPTER=on -DPython3_ROOT_DIR=C:\hostedtoolcache\windows\Python\3.10.11\x64 
        $env:match = cmake -L . | Select-String -Pattern OPENSIM_QUALIFIED_VERSION
        $version = $env:match.split('=')[1]
        echo $version
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Build opensim-core
      # Install now to avoid building bindings twice (issue when using Visual Studio 2019).
      run: |
        chdir $env:GITHUB_WORKSPACE\\build
        cmake --build . --config Release --target install -- /maxcpucount:4


    # - name: Update submodules
    #   run: git submodule update --init --recursive -- opensim-models opensim-visualizer Gui/opensim/threejs
      
    # - name: Build GUI
    #   id: build-gui
    #   run: |
    #     mkdir build
    #     cd build
    #     cmake ../ -G"Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=~/opensim-core-install -DANT_ARGS="-Dnbplatform.default.netbeans.dest.dir=C:/Program Files/NetBeans-12.3/netbeans;-Dnbplatform.default.harness.dir=C:/Program Files/NetBeans-12.3/netbeans/harness"
    #     cmake --build . --target CopyOpenSimCore --config Release
    #     cmake --build . --target CopyModels --config Release
    #     cmake --build . --target PrepareInstaller --config Release
    #     cmake --build . --target CopyJRE --config Release
    #     cmake --build . --target CopyVisualizer --config Release
    #     # Read the value of the cache variable storing the GUI build version.
    #     $env:match = cmake -L . | Select-String -Pattern OPENSIMGUI_BUILD_VERSION
    #     $VERSION = $env:match.split('=')[1]
    #     echo $VERSION
    #     echo "name=VERSION::$VERSION" >> $GITHUB_ENV
    #     echo "version=$VERSION" >> $env:GITHUB_OUTPUT
        
    # - name: Build GUI installer
    #   run: |
    #     cd Gui/opensim/dist/installer
    #     makensis.exe make_installer.nsi
    #     mv OpenSim-${{ steps.build-gui.outputs.version }}-win64.exe $env:GITHUB_WORKSPACE

    # - name: Upload GUI installer
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: OpenSim-${{ steps.build-gui.outputs.version }}-win64
    #     path: OpenSim-${{ steps.build-gui.outputs.version }}-win64.exe

    - name: Upload opensim-core
      uses: actions/upload-artifact@v4
      with:
        name: opensim-core-${{ github.event.pull_request.base.ref }}-win
        path: opensim-core-${{ github.event.pull_request.base.ref }}.zip
